In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('datasets/Classification/xrayfull.csv')

In [3]:
# data =  data.sample(frac=0.01, random_state=0)

In [4]:
data

Image Index   fold  Cardiomegaly  Emphysema  Effusion  Hernia  \
0       00000001_000.png  train           1.0        0.0       0.0     0.0   
1       00000001_001.png  train           1.0        1.0       0.0     0.0   
2       00000001_002.png  train           1.0        0.0       1.0     0.0   
3       00000002_000.png  train           0.0        0.0       0.0     0.0   
4       00000003_000.png  train           0.0        0.0       0.0     1.0   
...                  ...    ...           ...        ...       ...     ...   
112115  00030801_001.png  train           0.0        0.0       0.0     0.0   
112116  00030802_000.png    val           0.0        0.0       0.0     0.0   
112117  00030803_000.png  train           0.0        0.0       0.0     0.0   
112118  00030804_000.png  train           0.0        0.0       0.0     0.0   
112119  00030805_000.png  train           0.0        0.0       0.0     0.0   

        Infiltration  Mass  Nodule  Atelectasis  Pneumothorax  \
0                0.0   0.0     0.0          0.0           0.0   
1                0.0   0.0     0.0          0.0           0.0   
2                0.0   0.0     0.0          0.0           0.0   
3                0.0   0.0     0.0          0.0           0.0   
4                0.0   0.0     0.0          0.0           0.0   
...              ...   ...     ...          ...           ...   
112115           0.0   1.0     0.0          0.0           0.0   
112116           0.0   0.0     0.0          0.0           0.0   
112117           0.0   0.0     0.0          0.0           0.0   
112118           0.0   0.0     0.0          0.0           0.0   
112119           0.0   0.0     0.0          0.0           0.0   

        Pleural_Thickening  Pneumonia  Fibrosis  Edema  Consolidation  
0                      0.0        0.0       0.0    0.0            0.0  
1                      0.0        0.0       0.0    0.0            0.0  
2                      0.0        0.0       0.0    0.0            0.0  
3                      0.0        0.0       0.0    0.0            0.0  
4                      0.0        0.0       0.0    0.0            0.0  
...                    ...        ...       ...    ...            ...  
112115                 0.0        1.0       0.0    0.0            0.0  
112116                 0.0        0.0       0.0    0.0            0.0  
112117                 0.0        0.0       0.0    0.0            0.0  
112118                 0.0        0.0       0.0    0.0            0.0  
112119                 0.0        0.0       0.0    0.0            0.0  

[112120 rows x 16 columns]

In [5]:
data.drop(columns=['Image Index'], inplace=True)

In [6]:
data.rename(columns = {"fold": "Class"}, inplace=True)

In [7]:
clss = data["Class"].unique()
print(clss)

['train' 'test' 'val']


In [8]:
trainData = data.sample(frac=0.8, random_state=0)

In [9]:
testData = data.drop(trainData.index)

In [10]:
def probabilities(cls):
    n = len(trainData[trainData['Class'] == cls])
    d = {}
    for key in trainData.keys():
        if key != 'Class':
            dict = {}
            for i in set(trainData[key]):
                dict[i] = len(trainData[(trainData['Class'] == cls) & (trainData[key] == i)])/n
            d[key] = dict
    return d
probabilities('train')

{'Cardiomegaly': {0.0: 0.9749346676015043, 1.0: 0.02506533239849576},
 'Emphysema': {0.0: 0.9769902479444197, 1.0: 0.023009752055580344},
 'Effusion': {0.0: 0.8827044426030977, 1.0: 0.11729555739690228},
 'Hernia': {0.0: 0.9982471795525527, 1.0: 0.001752820447447256},
 'Infiltration': {0.0: 0.8224233539422525, 1.0: 0.17757664605774748},
 'Mass': {0.0: 0.9490885333673275, 1.0: 0.050911466632672576},
 'Nodule': {0.0: 0.9441328319204538, 1.0: 0.05586716807954618},
 'Atelectasis': {0.0: 0.8985116960928039, 1.0: 0.10148830390719613},
 'Pneumothorax': {0.0: 0.9531996940531583, 1.0: 0.04680030594684174},
 'Pleural_Thickening': {0.0: 0.9713174835872267, 1.0: 0.02868251641277328},
 'Pneumonia': {0.0: 0.9874434317037415, 1.0: 0.012556568296258525},
 'Fibrosis': {0.0: 0.9851806998534005, 1.0: 0.014819300146599528},
 'Edema': {0.0: 0.9784403084963987, 1.0: 0.02155969150360125},
 'Consolidation': {0.0: 0.9590796099177767, 1.0: 0.040920390082223215}}

In [11]:
prob = {}
for cls in set(data['Class']):
    prob[cls] = probabilities(cls)
print(prob)

{'test': {'Cardiomegaly': {0.0: 0.9741062479117942, 1.0: 0.025893752088205813}, 'Emphysema': {0.0: 0.9775030627018599, 1.0: 0.022496937298140104}, 'Effusion': {0.0: 0.8780487804878049, 1.0: 0.12195121951219512}, 'Hernia': {0.0: 0.9982180643724246, 1.0: 0.0017819356275754537}, 'Infiltration': {0.0: 0.8229201470096893, 1.0: 0.17707985299031073}, 'Mass': {0.0: 0.9498830604744404, 1.0: 0.05011693952555964}, 'Nodule': {0.0: 0.9401381000111371, 1.0: 0.059861899988862904}, 'Atelectasis': {0.0: 0.8919144670898764, 1.0: 0.10808553291012363}, 'Pneumothorax': {0.0: 0.9510524557300367, 1.0: 0.04894754426996325}, 'Pleural_Thickening': {0.0: 0.9678137877269184, 1.0: 0.03218621227308163}, 'Pneumonia': {0.0: 0.9891970152578238, 1.0: 0.010802984742176188}, 'Fibrosis': {0.0: 0.9842966922819913, 1.0: 0.015703307718008687}, 'Edema': {0.0: 0.981233990422096, 1.0: 0.018766009577904}, 'Consolidation': {0.0: 0.9563425771244014, 1.0: 0.043657422875598616}}, 'val': {'Cardiomegaly': {0.0: 0.9797372522823424, 1.0

In [12]:
def NaiveBayesClassifier(X):
    predcls = None
    maxval = 0
    for cls in prob.keys():
        val = 1
        for k in X.keys():
            temp = prob[cls].get(k,0)
            val *= temp.get(X[k],0)
        if val > maxval:
            maxval = val
            predcls = cls
    return predcls   

In [13]:
def confusion():
    classes = {}
    clss = trainData["Class"].unique()
    i = 0
    for clas in clss:
        classes[clas] = i
        i += 1
    n = len(classes)
    confmat = np.zeros(n*n)
    confmat = confmat.reshape(n,n)
    for _, d in testData.iterrows():
        y = d['Class']
        x = d.drop('Class')
        predy = NaiveBayesClassifier(x)
        confmat[classes[predy]][classes[y]] += 1
    return confmat

In [14]:
def accuracy(mat):
    n = len(mat)
    num = 0
    den = 0
    for i in range(n):
        num += mat[i][i]
        den += sum(mat[i])
    return num/den

In [15]:
def precision(mat, key):
    n = len(mat)
    num = mat[key][key]
    den = 0
    for i in range(n):
        den += mat[i][key]
    return num/den

In [16]:
def recall(mat, key):
    n = len(mat)
    num = mat[key][key]
    den = 0
    for i in range(n):
        den += mat[key][i]
    return num/den

In [17]:
def F1Score(p,r):
    return (2*(p*r))/(p + r)

In [18]:
mat = confusion() 
print(mat)
acc = accuracy(mat)
pre = precision(mat, 0)
rec = recall(mat, 0)
fscore = F1Score(pre, rec)
print(acc, pre, rec, fscore)

[[  629.   173.    79.]
 [ 4441.  1265.   607.]
 [10642.  3037.  1551.]]
0.1536300392436675 0.04003309572301426 0.713961407491487 0.07581510275417344
